displayName=Sailing Bad
author=YonwiPlugins
description=Hides Sailing from the skills tab and puts the total level back to 2277
tags=sailing,skills,total,level,2277,hide
version=
plugins=com.yonwiplugins.sailingbad.SailingBadPlugin
build=standard
